### PR TITLE
feat: automatically turn volume down when people talks

### PR DESCRIPTION
**Pull request by xytxxx**
This PR introduces a new feature that automatically lowers the music volume when users in the voice channel are speaking. The feature can be turned on/off through environment variables (default is off), and the target volume of when people are talking is also configurable (default is 70%).

Tested in personal Discord and found 70% volume leads to subtly better experience.

- [✓] I updated the changelog

### CODE REVIEW

**Comment by codetheweb** [comment]
#### :package: :robot: A new release has been made for this pull request.

To play around with this PR, pull `ghcr.io/museofficial/muse:pr-1096`.

Images are available for x86_64 and ARM64.

> Latest commit: 9b6240ddd0cafd47b070ac31de9d3554e8e7e3e5

**Comment by Codixer** [comment]
@Hazzajenko Would you be able to test and confirm this feature still works?

**Comment by Hazzajenko** [comment]
> @Hazzajenko Would you be able to test and confirm this feature still works?
> 

Sure I'll have a look after work today

**Comment by Hazzajenko** [comment]
I've updated the volume reduction feature to align with the standard approach of addons in muse:

- Removed the environment variables (`TURN_DOWN_VOLUME_WHEN_PEOPLE_SPEAK` and `TURN_DOWN_VOLUME_WHEN_PEOPLE_SPEAK_TARGET`) in favor of Discord slash commands
- Added two new config commands:
  - `/config set-reduce-vol-when-voice` to toggle the feature
  - `/config set-reduce-vol-when-voice-target` to set the reduction percentage (0-100)
- Settings are now stored in Prisma DB like other bot configurations

**Comment by Codixer** [comment]
LGTM

**Comment by codetheweb** [comment]
🚀 Released in [Release v2.10.0](https://github.com/museofficial/muse/releases/tag/v2.10.0).

**Pull request merged**
