### PR TITLE
feat: allow changing page size in /queue command

### LINKED ISSUE #1039: Feature Request: A config option to increase the number of songs shown when using the queue command
I was wondering if this might be possible, as it can be a bit of a pain to view what is queued without filling the chat with many queue commands

### PR DESCRIPTION
**Pull request by TiagoGrosso**
Closes #1039

- Adds an optional `page-size` option to the `/queue` command (min 1, max 50)
- Adds a new setting for the default queue page size

- [x] I updated the changelog

### CODE REVIEW

**Comment by codetheweb** [comment]
#### :package: :robot: A new release has been made for this pull request.

To play around with this PR, pull `ghcr.io/museofficial/muse:pr-1081`.

Images are available for x86_64 and ARM64.

> Latest commit: 9e27e7e66abbb3899a9ffce7e4c9807f636607ca

**Comment by TiagoGrosso** [comment]
Hey @Hazzajenko hoping you or another maintaner could take a look at this PR in the next few days :smiley:

**Comment by Hazzajenko** [comment]
Hey @TiagoGrosso, thanks for the great PR!

I've been testing it out with a large queue (60 songs) and I'm running into an error: "ope: Received one or more errors". Here's what I've found so far:

- The error occurs when I set the page size to 44 or higher.
- It works fine when displaying a smaller page size (like 43) or a later page (using `/queue page-size=44 page=2`).

This suggests we might be hitting a limit on the number of items that Discord embeds can display.

Here's some additional information from debugging:

Stack trace:

```js
"Error: Received one or more errors\n    at UnionValidator.handle (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\node_modules\\@sapphire\\shapeshift\\dist\\index.js:1104:23)\n    at UnionValidator.parse (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\node_modules\\@sapphire\\shapeshift\\dist\\index.js:212:88)\n    at EmbedBuilder.setDescription (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\node_modules\\@discordjs\\builders\\dist\\index.js:316:26)\n    at buildQueueEmbed (E:\\projects\\typescript\\muse\\src\\utils\\build-embed.ts:123:6)\n    at queue_default.execute (E:\\projects\\typescript\\muse\\src\\commands\\queue.ts:39:19)\n    at Client.<anonymous> (E:\\projects\\typescript\\muse\\src\\bot.ts:79:27)\n    at Client.emit (node:events:514:28)\n    at InteractionCreateAction.handle (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\src\\client\\actions\\InteractionCreate.js:97:12)\n    at Object.module.exports (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\src\\client\\websocket\\handlers\\INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\src\\client\\websocket\\WebSocketManager.js:354:29)"
```

Error details:

```json
{
    validator: "s.literal(V)",
    given: "...",
    expected: null,
},
{
    constraint: "s.string.lengthLessThanOrEqual",
    given: "...",
    expected: "expected.length <= 4096",
},
```

Looks like the message is exceeding a 4096 character limit imposed by Discord.

Could you try running your code with a large queue (similar to what I'm using) to see if you reproduce this issue? If so, we might need to consider lowering the maximum queue size or find a more efficient way to display the queue.

**Comment by TiagoGrosso** [comment]
> Hey @TiagoGrosso, thanks for the great PR!
> 
> I've been testing it out with a large queue (60 songs) and I'm running into an error: "ope: Received one or more errors". Here's what I've found so far:
> 
> * The error occurs when I set the page size to 44 or higher.
> * It works fine when displaying a smaller page size (like 43) or a later page (using `/queue page-size=44 page=2`).
> 
> This suggests we might be hitting a limit on the number of items that Discord embeds can display.
> 
> Here's some additional information from debugging:
> 
> Stack trace:
> 
> ```js
> "Error: Received one or more errors\n    at UnionValidator.handle (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\node_modules\\@sapphire\\shapeshift\\dist\\index.js:1104:23)\n    at UnionValidator.parse (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\node_modules\\@sapphire\\shapeshift\\dist\\index.js:212:88)\n    at EmbedBuilder.setDescription (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\node_modules\\@discordjs\\builders\\dist\\index.js:316:26)\n    at buildQueueEmbed (E:\\projects\\typescript\\muse\\src\\utils\\build-embed.ts:123:6)\n    at queue_default.execute (E:\\projects\\typescript\\muse\\src\\commands\\queue.ts:39:19)\n    at Client.<anonymous> (E:\\projects\\typescript\\muse\\src\\bot.ts:79:27)\n    at Client.emit (node:events:514:28)\n    at InteractionCreateAction.handle (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\src\\client\\actions\\InteractionCreate.js:97:12)\n    at Object.module.exports (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\src\\client\\websocket\\handlers\\INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (e:\\projects\\typescript\\muse\\node_modules\\discord.js\\src\\client\\websocket\\WebSocketManager.js:354:29)"
> ```
> 
> Error details:
> 
> ```json
> {
>     validator: "s.literal(V)",
>     given: "...",
>     expected: null,
> },
> {
>     constraint: "s.string.lengthLessThanOrEqual",
>     given: "...",
>     expected: "expected.length <= 4096",
> },
> ```
> 
> Looks like the message is exceeding a 4096 character limit imposed by Discord.
> 
> Could you try running your code with a large queue (similar to what I'm using) to see if you reproduce this issue? If so, we might need to consider lowering the maximum queue size or find a more efficient way to display the queue.

Hey! I did test with a large queue size but it might have had shorter music names perhaps. I'll look into this to find the best way. At worst I'll limit the page size to something like 30 instead of the current 50

**Comment by TiagoGrosso** [comment]
Limited page size to 30. Optimizing the display of the queue or cropping it when we hit the max 4096 chars seemed to yield more inconveniences than benefits. This already allows for 3x the page size, I think it's a nice improvement by itself

**Comment by codetheweb** [comment]
🚀 Released in [Release v2.9.4](https://github.com/museofficial/muse/releases/tag/v2.9.4).

**Pull request merged**
