### PR TITLE
Switch from ytdl-core to play-dl

### LINKED ISSUE #1018: Issues playing long videos, stop and crashes.
I've been trting to play long videos, as I really like compilations of videogame music, or studio ghibli, etc. But when I tried to do that it keeps crashing within seconds, up to a minute, then silence until it exits the VC.

I rune muse on Docker, and I did run the DEBUG setting, I do have some logs if you want to look at them. But I was investigating and checking if other bots had same issues and found this https://github.com/eritislami/evobot/issues/1176 which establishes that it's an issue with `ytdl-core`, and it seems like Muse uses that too, and on the mentioned issue they say that changing to `play-dl` would fix the issue.

I'm not sure how doable it would be to swap to `play-dl`, just opening this issue with hopes it could help.
I can send you logs or even links of videos I know give me issues, because every time I try to play them they stop in the exact same spot and refuses to keep playing.

Thank you for the bot, apart from this, it's a great bot!!

### PR DESCRIPTION
**Pull request by MarcoCoreDuo**
Closes #1018 
Should also resolve ytdl-core Issues #979 #945 #936 

~~Play-dl doesn't directly offer ts formats from livestreams like ytdl-core does, so I had to fetch and parse them myself from the m3u8 master playlist.~~ Also, play-dl always provides the best audio quality at the end of the format array for non-livestreams. ~~We could also replace node-fetch with native-fetch when the project is upgraded to Node 18 or later.~~

Edit: I replaced ffmpeg with play-dl stream for non-caching videos. This should actually resolve the issue mentioned in #1018. Also I don't know why the Lint check fails.

- [x] I updated the changelog

### CODE REVIEW

**Review by codetheweb — COMMENTED** [review]
thank you!

I tested this out and it seems like tracks aren't being cached anymore.

I'd also like to replace ytsr/spotify-web-api-node with play-dl, but that can be a separate PR if you want.

**Comment by MarcoCoreDuo** [comment]
> thank you!
> 
> I tested this out and it seems like tracks aren't being cached anymore.

That's strange. For me, caching works. I also checked it with the IDE debugger. Maybe you could send me the track you tested.

> I'd also like to replace ytsr/spotify-web-api-node with play-dl, but that can be a separate PR if you want.

I will look into that.

**Comment by alvarosdev** [comment]
Hello friend, I tried with the following docker, but no sound reaches Discord :/

```yaml
version: '3.4'

services:
  muse:
    image: codetheweb/muse:pr-1031
    restart: always
    volumes:
      - ./muse:/data
    env_file: .env
````
 
Logs 
```
muse-1  | 2024-07-01T04:44:23.823Z muse Caching video
muse-1  | 2024-07-01T04:44:24.094Z muse Spawned ffmpeg with ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -to 179 -i https://rr3---sn-uxgg5-852s.googlevideo.com/videoplayback?expire=1719830663&ei=JzSCZoW_HYqC-LAP-Z-R0AM&ip=x.x.x.x&id=o-AMRHIDYqhnTZvEsqtnyTb3myXNg5sp_9JFiESjtuBlml&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=zZ&mm=31%2C29&mn=sn-uxgg5-852s%2Csn-uxgg5-njaed&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=19&initcwndbps=1755000&bui=AbKP-1Mr55v3yset3AVpDAeGTzwPfDDWDOD1M00Zz5dAw_OAg_TmF_TOVYcrT1LmSL-Hyss45JWaUC13&spc=UWF9fwTsv2M1BdaI8yXIQzTO-aqjcZQ84x_et_IDtPCDy5i8mSLzMXgg0hTd&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=WwPH8zmNszPmCfEWbU5R7wIQ&rqh=1&gir=yes&clen=2837775&dur=178.261&lmt=1714668725008347&mt=1719808616&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=4402434&n=gg2Qg3z7Rpd0QvRX&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAMMuqUyc4IEvvwApHV339Nl79OthpDwFyN4OyFeVbwjRAiBWb_3y-DriWKUJs6olTkKz8mCbUQlCCwqJzrTztQyf7Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRAIgdsvg5whdr5Fx-NZHXlMYGdw0wtO8xUlsQm81cvj778ACIDtoLXdD0Q2bBr83wJ-8FJC7x3KEy6PR2S_v2Lu1UL5C -acodec libopus -vn -f webm -filter:a volume=-8.9099998dB pipe:1
```

That URL (rr3---blabla...) returns an HTTP 403 Forbidden error code.

**Comment by MarcoCoreDuo** [comment]
> Hello friend, I tried with the following docker, but no sound reaches Discord :/
> 
> ```yaml
> version: '3.4'
> 
> services:
>   muse:
>     image: codetheweb/muse:pr-1031
>     restart: always
>     volumes:
>       - ./muse:/data
>     env_file: .env
> ````
>  
> Logs 
> ```
> muse-1  | 2024-07-01T04:44:23.823Z muse Caching video
> muse-1  | 2024-07-01T04:44:24.094Z muse Spawned ffmpeg with ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -to 179 -i https://rr3---sn-uxgg5-852s.googlevideo.com/videoplayback?expire=1719830663&ei=JzSCZoW_HYqC-LAP-Z-R0AM&ip=x.x.x.x&id=o-AMRHIDYqhnTZvEsqtnyTb3myXNg5sp_9JFiESjtuBlml&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=zZ&mm=31%2C29&mn=sn-uxgg5-852s%2Csn-uxgg5-njaed&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=19&initcwndbps=1755000&bui=AbKP-1Mr55v3yset3AVpDAeGTzwPfDDWDOD1M00Zz5dAw_OAg_TmF_TOVYcrT1LmSL-Hyss45JWaUC13&spc=UWF9fwTsv2M1BdaI8yXIQzTO-aqjcZQ84x_et_IDtPCDy5i8mSLzMXgg0hTd&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=WwPH8zmNszPmCfEWbU5R7wIQ&rqh=1&gir=yes&clen=2837775&dur=178.261&lmt=1714668725008347&mt=1719808616&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=4402434&n=gg2Qg3z7Rpd0QvRX&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAMMuqUyc4IEvvwApHV339Nl79OthpDwFyN4OyFeVbwjRAiBWb_3y-DriWKUJs6olTkKz8mCbUQlCCwqJzrTztQyf7Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRAIgdsvg5whdr5Fx-NZHXlMYGdw0wtO8xUlsQm81cvj778ACIDtoLXdD0Q2bBr83wJ-8FJC7x3KEy6PR2S_v2Lu1UL5C -acodec libopus -vn -f webm -filter:a volume=-8.9099998dB pipe:1
> ```
> 
> That URL (rr3---blabla...) returns an HTTP 403 Forbidden error code.

Hi, sadly play-dl broke two weeks ago because YouTube changed something. We have to wait for a fix.

**Comment by Codixer** [comment]
@MarcoCoreDuo 
Hey Marco! I am going past all PR's and checking this one, would you like to still work on this? Or can this be closed?

**Pull request closed without merging**
