### PR TITLE
Very Basic support of SoundClound

### LINKED ISSUE #418: SoundCloud support
Support SoundCloud as well along with YouTube and Spotify.
YouTube-dl already supports SoundCloud the same way as YouTube.

### PR DESCRIPTION
**Pull request by Kapppa**
Closes #418

Adds support for SoundCloud, this is very basic support of it. Currently only supports urls no searching.

### CODE REVIEW

**Comment by codetheweb** [comment]
thanks! unfortunately this doesn't seem to be working for me, e.g. with https://soundcloud.com/joeyvalenceandbrae/packapunch-feat-danny-brown-1.

It adds the track to the queue and shows it as playing but the audio doesn't seem to make it to Discord.

**Comment by Kapppa** [comment]
> thanks! unfortunately this doesn't seem to be working for me, e.g. with https://soundcloud.com/joeyvalenceandbrae/packapunch-feat-danny-brown-1.
> 
> It adds the track to the queue and shows it as playing but the audio doesn't seem to make it to Discord.

Works fine for me on my end. Is the IP the bot is running on blocked from soundcloud?

**Comment by Codixer** [comment]
@Kapppa would you have time to test and update your PR?

**Comment by DaanSelen** [comment]
What is the status of this PR?

**Comment by Codixer** [comment]
@DaanSelen I gotta know if the changes work.

**Comment by DaanSelen** [comment]
@Kapppa how can we verify?

**Review by DaanSelen — COMMENTED** [review]
It works! But I already found some bugs!

**Comment by DaanSelen** [comment]
I'm very hopeful for this method. But it has become out of date, perhaps if we revise the code to the current version. I am not competent enough for that but perhaps someone is willing?

**Comment by Codixer** [comment]
We'll see if someone wants to work on this update. I'll check myself as well, but no promises yet.

**Comment by DaanSelen** [comment]
> We'll see if someone wants to work on this update. I'll check myself as well, but no promises yet.

For me this would make Muse complete, I now need to run multiple bots for all providers.

**Pull request closed without merging**
