### PR TITLE
feat: allow running without spotify

### LINKED ISSUE #835: Using without Spotify?
Hi!

This is a great project and looks very nice.
However, is it possible to run this app without Spotify? By providing only "" as secret and API, it still tries to log in, which I would not prefer as I don't use Spotify.

**Runtime**
I'm running Muse:
- [X ] Inside a Docker container

**Versions**
- Muse: 2.1.7
- Docker (if applicable): Docker Desktop 4.14.1
- OS: Windows 10 64bit

### PR DESCRIPTION
**Pull request by sofushn**
Closes #835 

This PR allows muse to run without a Spotify client ID and secret.

The command will responde with `🚫 ope: Spotify is not enabled!` if a user tries to query a song with a Spotify URL.

### Logic changes

To allow for cases where Spotify isn't available two methods required changes.

__`addToQueue()`__: The logic for determining which source to fetch songs from has been moved to the `getSongs` service class in `get-songs.ts`.  Songs are fetched through a single method named `getSongs()` which include the old logic from `addToQueue()`, all other methods in the class has been made private.

__`getYouTubeAndSpotifySuggestionsFor()`__: Has been refactored, all Spotify logic has been moved to the end of the method (fetching still happens asynchrony at the beginning).

PR also updates `YoutubeAPI.search()` method to return an empty array if no match is found for the search query. This allows for better error handling other places in the code.

- [ ] I updated the changelog

### CODE REVIEW

**Comment by codetheweb** [comment]
#### :package: :robot: A new release has been made for this pull request.

To play around with this PR, pull `ghcr.io/museofficial/muse:pr-1092`.

Images are available for x86_64 and ARM64.

> Latest commit: dff5d56085dd1eca59d189af13f9b22b57c8a165

**Comment by Codixer** [comment]
@sofushn Thanks for the PR, it currently lgtm. But to confirm something, this does still display the spotify query in the search function. Even if spotify is disabled?

**Comment by sofushn** [comment]
> Thanks for the PR, it currently lgtm. But to confirm something, this does still display the spotify query in the search function. Even if spotify is disabled?

It's quite a long time since I wrote this PR, if I remember correctly I just show an error to the user if they try to search with a Spotify URL otherwise the whole Spotify part is ignored.

**Comment by Codixer** [comment]
No worries @sofushn, I was just given access to this repo. I am going through everything to check what has been updated. What still needs to be done and so on and so forth.

**Comment by Codixer** [comment]
> For reference this is how the query result looks (fixed the Spotify URL prompt) image

Ah thanks, that's what I had to know. Will test this later today.

**Comment by codetheweb** [comment]
🚀 Released in [Release v2.10.0](https://github.com/museofficial/muse/releases/tag/v2.10.0).

**Pull request merged**
